name: Build, Test & Upload

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'microsoft'

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Upload Nightly Build
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: skript-nightly
          path: build/libs/**
