name: Build, Test & Upload

on:
  push:
    branches:
      - master
      - 'scroll/**'
      - 'parser/**'
  pull_request:

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build project
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Upload Nightly Build
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: skript-nightly
          path: build/libs/**
